---
- name: "Extract artifact into EC2 Instance" 
  unarchive:
    src: ~/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
    dest: .
- name: "Start the app"
  shell: |
    pm2 stop all
    pm2 start npm -- start    